## 미리 학습된 언어 모델

### 언어 모델
언어 모델은 **단어 시퀀스에 확률을 부여**하는 모델이다.
- 풀어서 단어 시퀀스를 입력받아 해당 시퀀스가 얼마나 그럴듯한지 확률을 출력하는 모델

**결합확률**과 **조건부확률**로 나타낸다면

**전체 단어 시퀀스**가 나타날 확률은 **이전 단어들이 주어졌을 때** 다음 단어가 **등장할 확률의 연쇄**이다. 

언어 모델은 **이전 단어들이 주어졌을 깨 다음 단어가 나타날 확률을 부여**하는 모델이다.



**순방향 언어 모델**

이전 단어들(컨텍스트)가 주어졌을 때 다음 단어 맞히기
GPT,ELMo



**역방향 언어 모델**

문장을 뒤에서 앞으로 계산하는 모델
- ELMo: 순방향과 역방향 모두 사용

### 넓은 의미의 언어 모델
  P(w|context)

컨텍스트가 전제된 상태에서 특정 단어가 나타날 조건부 확률

**마스크 언어 모델**

학습 대상 문장에 빈칸을 만들어 놓고 해당 빈칸에 올 단어로 적절한 단어가 무엇일지 분류하는 과정
- BERT

문장 전체의 맥락을 참고할 수 있다는 장점(**양방향 성질**)

**스킵-그램 모델**

어떤 단어 **앞뒤에 특정 범위를 정해** 두고 이 **범위 내에서 어떤 단어**들이 올지 분류하는 과정으로 학습

컨텍스트로 설정한 단어 주변에 어떤 단어들이 분포해 있는지를 학습한다
- Word2Vec

### 언어모델의 유용성

## 트랜스포모 살펴보기


트렌스 포머는 시퀀스-투-시퀀스모델

### 시퀀스-투-시퀀스
시퀀스-투-시퀀스란 **특정 속성을 지닌 시퀀스**를 **다른 속성의 시퀀스로 변환**하는 작업

시퀀스: 단어 같은 무언가의 나열 
### 인코더와 디코더
트랜스포머는 시퀀스-투-시퀀스에 특화된 모델
- 사용예: 기온의 시퀀스-> 태풍 발생 여부의 시퀀스

인코더와 디코더로 구성

**인코더**

소스 시퀀스 정보를 압축(인코딩)

**디코더**

시퀀스 정보를 받아서 타깃 시퀀스를 생성(디코딩)


### 모델 학습과 인퍼런스

트랜스포머는 인코더와 디코ㅔ 입력이 주어졌을 때 정답에 해당하는 단어의 확률 값을 높이는 방식으로 학습

세부 예시는 책 참조(74~76)

### 트렌스포머 블록
**블록(레이어)** 인(디)코더에 반복되는 요소를 나타낸 것

트렌스포어의 인코더는 블록이 수십 개 쌓아 구성

인코더 블록: 멜티 헤드 어텐션, 피드포워드 뉴럴네트워크, 전자 연결 및 레이어 정규화 등 3가지로 구성

디코더 블록: 마스크를 적용한 멀티 헤드 어텐션이 인코더와 다르고 인코더가 보내온 정보와 디코더 입력을 함께 이용해 멀티 헤드 어텐션을 수행할 모듈이 추가


### 셀프 어텐션
멀티헤드 어텐션 = 셀프 어텐션
트렌스포머의 경쟁력원천

**어텐션**: 
- 시퀀스 입력에 수행하는 기계학습 방법
- 중요한 요소에 집중하고 아닌 요소는 무시해 태스크 수행-> 성능 UP

기계번역에 어텐션을 도입하면 **디코딩**에 도움이 되는 단어 위주로 **취사 선택**하여 번역 품질을 올림

셀프 어텐션은 자신엥게 수행하는 어텐션 기법

**합성곱 긴경망(CNN)**

합성곱 필터를 이용하여 지역적인 특성을 잡아내는 모델

CNN은 학성곱 필터 크기를 넘어서는 문맥은 읽어내기 어렵다는 단점

**순환 신경망(RNN)**

시퀀스 정보를 압축하는 데 강점

But 마지막 단어에 집중하고 전반부 단어는 잊는 경향

**특징 및 장점**

어제 카페 갔었어 거기 사람 많더라

거기는 카페와 갔었어에 크게 반영

카페 역시 거기와 갔었어 크게 반영


- 개별 단어와 전체 입력 시퀀스를 대상으로 어텐션 계산을 수행해 문맥 전체를 고려하므로 지역적인 문맥만 보는 CNN보다 강점
- 모든 경우의 수를 고려하기(1대1로 바라보게 함) 때문에 길어져도 왜곡이 적음(RNN단점 극복)


**계산**

셀프 어텐션은 쿼리, 키, 밸류가 서로 영향을 주고 받으면서 문장의 의미를 계산한다.

밸퓨 벡터들을 가중합하는 방식으로 계산

## 셀프 어텐션 동작 원리

## 트랜스포머에 적용된 기술들

### 피드포워드 뉴럴 네트워크
멀티 헤드 어텐션의 개별 출력 벡터가 입력이 됨

입력층 출력층 은닉층으로 구성

활성 함수는 **ReLu**임

- ReLu:양수는 그대로 출력하고 음수는 0으로 치환해서 무시함

**학습대상** 

가중치와 바이어스 for task(ex:기계학습)을 잘하는 방향


In [3]:
#피드포워드 뉴럴 네트워크 계산 예시
import torch as to

x=to.tensor([2,1]) #입력
w1=to.tensor([[3,2,-4],[2,-3,1]])#입력층-은닉층 가중치
b1=1#입력층-은닉층 바이어스
w2=to.tensor([[-1,1],[1,2],[3,1]])#은닉층-출력층 가중치
b2=-1#은닉층-출력층 바이어스

h_preact=to.matmul(x,w1)+b1
h=to.nn.functional.relu(h_preact)
y=to.matmul(h, w2) + b2
print(h_preact )
print(h )
print( y)

tensor([ 9,  2, -6])
tensor([9, 2, 0])
tensor([-8, 12])


**잔차 연결**

블록이나 레이어를 하나 건너뛰는 경로를 하나 두는 것(F(x)+x로 실현)

모델이 다양한 관점에서 블록 걔산을 수행하게 된다.

**레이어 정규화**

미니 배치의 인스턴스별로 정규화를 수행하는 방법
학습이 안정되고 속도가 빨라지는 효과


In [4]:
#레이어 정규화 예시
import torch
input=torch.tensor([[1.0,2.0,3.0],[1,1,1]])
m=torch.nn.LayerNorm(input.shape[-1])
output=m(input)

print(output)

tensor([[-1.2247,  0.0000,  1.2247],
        [ 0.0000,  0.0000,  0.0000]], grad_fn=<NativeLayerNormBackward0>)


### 모델 학습 기법

**드롭아웃**

**과적합을 방지**하고자 뉴런의 일부를 확률적으로 0으로 대치하여 계산에서 제외함

In [5]:
#드롭아웃
import torch
m=torch.nn.Dropout(p=0.2) #20%로 드롭 아웃 수행
input=torch.randn(1,10)
output=m(input)

print(input)
output

#드롭아웃 결과 80%는 1.25배로 증가함
#학습과정에만 적용됨

tensor([[-0.2999,  0.1314,  0.8110, -0.5142,  0.0260,  0.0054,  1.1157, -0.4485,
          0.7833, -0.2591]])


tensor([[-0.0000,  0.1642,  1.0137, -0.6428,  0.0325,  0.0068,  0.0000, -0.5606,
          0.9791, -0.3238]])

**아담 옵티마이저**

딥러닝 학습은 오차의 최소하는 방향으로 파라미터를 업데이트 과정
- 오차를 **손실**
- 오차를 최소화 하는 방향을 **그레이디언트**
- 최소화 하는 과정을 **최적화**
- **파라미터**: 모델 구성요소
  - 남자 키 정규 본로라는 모델
    - 평균키, 펴즌편차가 파라미터
- **순전파**:모델을 처음에서 끝 방향으로 계산
- **역전파**: 순전파의 역순으로 계산 

**아담옵티마이저**: 

파라미터를 업데이트 할때의 보폭을 최적화 하는 도구 중 하나

그레디언트는 관성을 가지고
보폭은 안가본곳은 크게 가본곳은 작게

In [ ]:
#아담 옵티마이저
from torch.optim import Adam
optimizer=Adam(model.parameters(), lr=model.learning_rate)
#learning_rate은 최초의 보폭

## BERT와 GPT 비교

### BERT와 GPT
GPT
- 일방향
- 문장 생성

BERT
- 양방향 성격
- 문장의 의미 추출

### GPT 구조
- 트랜스포머에서 인코더를 제외하고 디코더만 사용
- 디코더에서도 인코더 정보를 받는 부분 없음

### BERT 구조
- 트랜스포머에서 인코더만 사용

### 최근 트렌드
- 모델 크기 증가 추세
- 모델의 크기 줄이려는 노력

## 단어/문장을 벡터로 변환하기

### 파인튜닝
다운스트림 데이터로 업데이트하는 과정

**문장 벡터 활용: 문서 분류 등**

**단어 벡터 활용: 개체명 인식 등**

### 코드

#### 1단계

In [1]:
!pip install ratsnlp

     |████████████████████████████████| 42 kB 1.1 MB/s 
     |████████████████████████████████| 57 kB 6.8 MB/s 
     |████████████████████████████████| 2.8 MB 52.7 MB/s 
     |████████████████████████████████| 398 kB 71.1 MB/s 
     |████████████████████████████████| 8.0 MB 22.9 MB/s 
     |████████████████████████████████| 806 kB 64.9 MB/s 
     |████████████████████████████████| 636 kB 61.2 MB/s 
     |████████████████████████████████| 829 kB 39.7 MB/s 
     |████████████████████████████████| 136 kB 68.9 MB/s 
     |██████████████████████████████▎ | 834.1 MB 1.1 MB/s eta 0:00:43tcmalloc: large alloc 1147494400 bytes == 0x3d5a000 @  0x7f60cc04c615 0x592b76 0x4df71e 0x59afff 0x515655 0x549576 0x593fce 0x548ae9 0x51566f 0x549576 0x593fce 0x548ae9 0x5127f1 0x598e3b 0x511f68 0x598e3b 0x511f68 0x598e3b 0x511f68 0x4bc98a 0x532e76 0x594b72 0x515600 0x549576 0x593fce 0x548ae9 0x5127f1 0x549576 0x593fce 0x5118f8 0x593dd7
     |████████████████████████████████| 881.9 MB 17 kB/s 
     |█████████

#### 2단계 토크나이저 초기화

In [4]:
#토크나이저 선언
## BERT(kcbert-base) 모델이 쓰는 토크나이저를 선언
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained(
    "beomi/kcbert-base",
    do_lower_case=False,
)

In [5]:
# BERT(kcbert-base) 모델을 읽기
from transformers import BertConfig, BertModel
pretrained_model_config = BertConfig.from_pretrained(
    "beomi/kcbert-base"
)
model = BertModel.from_pretrained(
    "beomi/kcbert-base",
    config=pretrained_model_config,
)


Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Some weights of the model checkpoint at beomi/kcbert-base were not used when initializing BertModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.weight', 'cls.predictions.decoder.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [6]:
#pretrained_model_config의 내용을 확인
pretrained_model_config

BertConfig {
  "_name_or_path": "beomi/kcbert-base",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 300,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "transformers_version": "4.10.0",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 30000
}

#### 3단계 입력값 만들기

In [7]:
sentences = ["안녕하세요", "하이!"]
features = tokenizer(
    sentences,
    max_length=10,
    padding="max_length",
    truncation=True,
)

In [8]:
features.keys()
#features['input_ids']

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

BERT 임베딩 추출

In [12]:
#피처를 토치 텐서로 변환
import torch
features = {k: torch.tensor(v) for k, v in features.items()}
#BERT 모델에 features를 입력해 계산
outputs = model(**features)

#BERT 마지막 레이어의 단어 수준 벡터들을 확인
outputs.last_hidden_state
# #BERT 마지막 레이어의 문서 수준 벡터를 확인
# outputs.pooler_output

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  This is separate from the ipykernel package so we can avoid doing imports until


tensor([[[-0.6969, -0.8248,  1.7512,  ..., -0.3732,  0.7399,  1.1907],
         [-1.4803, -0.4398,  0.9444,  ..., -0.7405, -0.0211,  1.3064],
         [-1.4300, -0.5033, -0.2069,  ...,  0.1285, -0.2611,  1.6057],
         ...,
         [-1.4406,  0.3431,  1.4043,  ..., -0.0565,  0.8450, -0.2170],
         [-1.3625, -0.2404,  1.1757,  ...,  0.8876, -0.1054,  0.0734],
         [-1.4244,  0.1518,  1.2920,  ...,  0.0245,  0.7572,  0.0080]],

        [[ 0.9371, -1.4749,  1.7351,  ..., -0.3426,  0.8050,  0.4031],
         [ 1.6095, -1.7269,  2.7936,  ...,  0.3100, -0.4787, -1.2491],
         [ 0.4861, -0.4569,  0.5712,  ..., -0.1769,  1.1253, -0.2756],
         ...,
         [ 1.2362, -0.6181,  2.0906,  ...,  1.3677,  0.8132, -0.2742],
         [ 0.5409, -0.9652,  1.6237,  ...,  1.2395,  0.9185,  0.1782],
         [ 1.9001, -0.5859,  3.0156,  ...,  1.4967,  0.1924, -0.4448]]],
       grad_fn=<NativeLayerNormBackward0>)