# 선호도 데이터 활용

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
# 데이터 불러오기
like = pd.read_csv('/content/like.csv')
like.columns = ['talk','book','travel','school','tall','skin','muscle','like_level']
like.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   talk        14 non-null     int64 
 1   book        14 non-null     int64 
 2   travel      14 non-null     int64 
 3   school      14 non-null     int64 
 4   tall        14 non-null     int64 
 5   skin        14 non-null     int64 
 6   muscle      14 non-null     int64 
 7   like_level  14 non-null     object
dtypes: int64(7), object(1)
memory usage: 1.0+ KB


In [3]:
# feature와 label 지정
X = np.array(like.drop('like_level', axis=1))
y = np.array(like.like_level)

X.shape,y.shape

((14, 7), (14,))

In [4]:
# 정규화
scaler = StandardScaler()
X = scaler.fit(X).transform(X)
X

array([[-1.26962211,  1.34164079, -0.8461218 , -0.98782916,  2.06644812,
         1.29927838, -0.59160798],
       [ 0.21160368, -0.36590203,  0.57536283, -0.3592106 ,  0.04805693,
        -0.09994449,  1.77482393],
       [-0.28213825, -0.93508297,  1.04919104,  0.26940795, -0.62474013,
         0.36646313,  1.18321596],
       [ 1.69282948, -0.36590203,  0.10153462, -1.61644772, -1.29753719,
        -1.96557498, -1.77482393],
       [-0.28213825,  0.77245985, -1.31995001,  0.89802651,  0.720854  ,
         0.83287076,  0.        ],
       [ 0.70534562, -1.50426391,  0.10153462, -0.98782916, -1.29753719,
        -1.03275974, -1.77482393],
       [-0.77588018,  1.91082173,  0.10153462,  0.26940795,  0.04805693,
         0.83287076,  0.        ],
       [-1.26962211,  0.20327891,  1.52301925,  0.26940795, -1.29753719,
         0.36646313,  0.59160798],
       [ 1.19908755, -0.93508297, -1.79377823,  1.52664507,  0.04805693,
        -1.03275974, -0.59160798],
       [-0.28213825,  0.7724

In [5]:
# 모델 학습
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X,y)

KNeighborsClassifier()

In [6]:
# 원래 데이터를 넣어서 예측
y_pred = knn.predict(X)
y_pred

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [7]:
y

array(['1타입', '2타입', '2타입', '3타입', '1타입', '3타입', '1타입', '2타입', '3타입',
       '1타입', '3타입', '1타입', '2타입', '3타입'], dtype=object)

In [8]:
# 모델 평가
print(f' confusion matrix : \n {confusion_matrix(y,y_pred)} \n')
print(f' classification report : \n {classification_report(y,y_pred)} \n')

 confusion matrix : 
 [[5 0 0]
 [0 4 0]
 [0 0 5]] 

 classification report : 
               precision    recall  f1-score   support

         1타입       1.00      1.00      1.00         5
         2타입       1.00      1.00      1.00         4
         3타입       1.00      1.00      1.00         5

    accuracy                           1.00        14
   macro avg       1.00      1.00      1.00        14
weighted avg       1.00      1.00      1.00        14
 

