# 01.개념

## 01)전처리

In [1]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

weather=['Rainy','Rainy','Sunny','Sunny','Sunny','Overcast','Overcast','Overcast','Overcast','Rainy',\
         'Rainy','Rainy','Sunny','Sunny']
temp=['Cool','Mild','Hot','Hot','Mild','Cool','Hot','Hot','Mild','Cool','Mild','Mild','Cool','Mild']
play=['No','No','No','No','No','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes']

In [2]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder() #정수 인코딩

weather_encoded=LE.fit_transform(weather)
temp_encoded=LE.fit_transform(temp)
data=np.c_[weather_encoded,temp_encoded]
#np.c_:행으로 펴현된 젓을 열 단위로 붙여 주는 코드
target=LE.fit_transform(play)

print(data)
print(target)

[[1 0]
 [1 2]
 [2 1]
 [2 1]
 [2 2]
 [0 0]
 [0 1]
 [0 1]
 [0 2]
 [1 0]
 [1 2]
 [1 2]
 [2 0]
 [2 2]]
[0 0 0 0 0 1 1 1 1 1 1 1 1 1]


## 02)학습

In [4]:
from sklearn.naive_bayes import CategoricalNB
CNB=CategoricalNB(alpha=0) #aplha=0: smoothing을 0으로 설정/ 예외적 상황
CNB.fit(data, target)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:557: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10
  % _ALPHA_MIN


CategoricalNB(alpha=0)

## 03)예측

In [5]:
CNB.predict_proba(data)#predict_proba: 확률값을 알려줌

array([[2.85714286e-01, 7.14285714e-01],
       [3.75000000e-01, 6.25000000e-01],
       [7.29729730e-01, 2.70270270e-01],
       [7.29729730e-01, 2.70270270e-01],
       [5.74468085e-01, 4.25531915e-01],
       [1.50000000e-11, 1.00000000e+00],
       [4.50000000e-11, 1.00000000e+00],
       [4.50000000e-11, 1.00000000e+00],
       [2.25000000e-11, 1.00000000e+00],
       [2.85714286e-01, 7.14285714e-01],
       [3.75000000e-01, 6.25000000e-01],
       [3.75000000e-01, 6.25000000e-01],
       [4.73684211e-01, 5.26315789e-01],
       [5.74468085e-01, 4.25531915e-01]])

In [6]:
CNB.predict(data) #예측값

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [7]:
x=CNB.predict_proba(data) 
np.round(x,4)

array([[0.2857, 0.7143],
       [0.375 , 0.625 ],
       [0.7297, 0.2703],
       [0.7297, 0.2703],
       [0.5745, 0.4255],
       [0.    , 1.    ],
       [0.    , 1.    ],
       [0.    , 1.    ],
       [0.    , 1.    ],
       [0.2857, 0.7143],
       [0.375 , 0.625 ],
       [0.375 , 0.625 ],
       [0.4737, 0.5263],
       [0.5745, 0.4255]])

In [8]:
CNB.predict(data), target

(array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0]),
 array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

##04) 평가

In [9]:
CNB.score(data, target)#분류정확도 score

0.7857142857142857

In [10]:
CNB.classes_ #클래스 종류

array([0, 1])

In [11]:
CNB.class_count_ #클래스별 원소 갯수

array([5., 9.])

In [12]:
np.exp(CNB.class_log_prior_)
#클래스 사전확률(log)>>원래값 변환

array([0.35714286, 0.64285714])

In [13]:
#기능도,우도()저장
x=np.exp(CNB.feature_log_prob_)
9np.round(x,4)

array([[[0.    , 0.4   , 0.6   ],
        [0.4444, 0.3333, 0.2222]],

       [[0.2   , 0.4   , 0.4   ],
        [0.3333, 0.2222, 0.4444]]])

# 02.이진분류

## 01)전처리

In [14]:
import numpy as np
import pandas as pd

df=pd.read_csv('/content/mushrooms.csv')
print(type(df), df.shape)

<class 'pandas.core.frame.DataFrame'> (8124, 23)


In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [16]:
df.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [17]:
df['class']

0       p
1       e
2       e
3       p
4       e
       ..
8119    e
8120    e
8121    e
8122    p
8123    e
Name: class, Length: 8124, dtype: object

In [18]:
df['class'].value_counts()

e    4208
p    3916
Name: class, dtype: int64

In [19]:
df['cap-shape'].value_counts().index

Index(['x', 'f', 'k', 'b', 's', 'c'], dtype='object')

In [20]:
x=df['cap-shape'].value_counts().index
y=df['cap-shape'].value_counts()
plt.bar(x,y,color='red')
plt.show()

In [21]:
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [23]:
data=df.loc[:,'cap-shape':'habitat']
data

cap-shape cap-surface cap-color bruises odor gill-attachment  \
0            x           s         n       t    p               f   
1            x           s         y       t    a               f   
2            b           s         w       t    l               f   
3            x           y         w       t    p               f   
4            x           s         g       f    n               f   
...        ...         ...       ...     ...  ...             ...   
8119         k           s         n       f    n               a   
8120         x           s         n       f    n               a   
8121         f           s         n       f    n               a   
8122         k           y         n       f    y               f   
8123         x           s         n       f    n               a   

     gill-spacing gill-size gill-color stalk-shape  ...  \
0               c         n          k           e  ...   
1               c         b          k           e  ...   
2               c         b          n           e  ...   
3               c         n          n           e  ...   
4               w         b          k           t  ...   
...           ...       ...        ...         ...  ...   
8119            c         b          y           e  ...   
8120            c         b          y           e  ...   
8121            c         b          n           e  ...   
8122            c         n          b           t  ...   
8123            c         b          y           e  ...   

     stalk-surface-below-ring stalk-color-above-ring stalk-color-below-ring  \
0                           s                      w                      w   
1                           s                      w                      w   
2                           s                      w                      w   
3                           s                      w                      w   
4                           s                      w                      w   
...                       ...                    ...                    ...   
8119                        s                      o                      o   
8120                        s                      o                      o   
8121                        s                      o                      o   
8122                        k                      w                      w   
8123                        s                      o                      o   

     veil-type veil-color ring-number ring-type spore-print-color population  \
0            p          w           o         p                 k          s   
1            p          w           o         p                 n          n   
2            p          w           o         p                 n          n   
3            p          w           o         p                 k          s   
4            p          w           o         e                 n          a   
...        ...        ...         ...       ...               ...        ...   
8119         p          o           o         p                 b          c   
8120         p          n           o         p                 b          v   
8121         p          o           o         p                 b          c   
8122         p          w           o         e                 w          v   
8123         p          o           o         p                 o          c   

     habitat  
0          u  
1          g  
2          m  
3          u  
4          g  
...      ...  
8119       l  
8120       l  
8121       l  
8122       l  
8123       l  

[8124 rows x 22 columns]

In [24]:
target=df['class']

In [25]:
data=np.array(data)
target=np.array(target)

data, target

(array([['x', 's', 'n', ..., 'k', 's', 'u'],
        ['x', 's', 'y', ..., 'n', 'n', 'g'],
        ['b', 's', 'w', ..., 'n', 'n', 'm'],
        ...,
        ['f', 's', 'n', ..., 'b', 'c', 'l'],
        ['k', 'y', 'n', ..., 'w', 'v', 'l'],
        ['x', 's', 'n', ..., 'o', 'c', 'l']], dtype=object),
 array(['p', 'e', 'e', ..., 'e', 'p', 'e'], dtype=object))

In [26]:
data.shape, target.shape

((8124, 22), (8124,))

In [27]:
np.unique(data[:,0], return_counts=True)

(array(['b', 'c', 'f', 'k', 's', 'x'], dtype=object),
 array([ 452,    4, 3152,  828,   32, 3656]))

In [28]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()

for i in range(len(data[0])):
    data[:,i]=LE.fit_transform(data[:,i])
    
target=LE.fit_transform(target)

data, target

(array([[5, 2, 4, ..., 2, 3, 5],
        [5, 2, 9, ..., 3, 2, 1],
        [0, 2, 8, ..., 3, 2, 3],
        ...,
        [2, 2, 4, ..., 0, 1, 2],
        [3, 3, 4, ..., 7, 4, 2],
        [5, 2, 4, ..., 4, 1, 2]], dtype=object),
 array([1, 0, 0, ..., 0, 1, 0]))

## 02)학습(통으로)

In [29]:
from sklearn.naive_bayes import CategoricalNB
CNB=CategoricalNB()
CNB.fit(data, target) #fit학습
print(CNB.score(data, target))

0.9566715903495815


## 02)학습(나누어)

In [30]:
from sklearn.model_selection import train_test_split
train_data, test_data, train_target, test_target=train_test_split(data, target, stratify=target, random_state=42) #random_state:seed 값 설정

train_data.shape, test_data.shape, train_target.shape, test_target.shape

((6093, 22), (2031, 22), (6093,), (2031,))

In [31]:
from sklearn.naive_bayes import CategoricalNB
CNB=CategoricalNB()
CNB.fit(train_data, train_target) #학습
print(CNB.score(train_data, train_target))
print(CNB.score(test_data, test_target))

0.9537173806006893
0.9527326440177253


In [32]:
print(CNB.predict(test_data[:20]))
print(test_target[:20])

[0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 1 1 0]
[0 1 0 1 1 0 1 1 0 1 0 0 0 0 1 1 0 1 1 0]
